<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <ItemGroup>
    <ProjectReference Include="..\Backend\Backend.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.3" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>dfb9a946-f074-4e60-bae5-669ea8004953</UserSecretsId>
  </PropertyGroup>

</Project>
